[postgres]
url = "postgresql://postgres:Nikaliva2026@db.uwfiquypgbonluztkbxo.supabase.co:5432/postgres"

[connections.postgres]
url = "postgresql://postgres:Nikaliva2026@db.uwfiquypgbonluztkbxo.supabase.co:5432/postgres"
