[postgres]
url = "postgresql://postgres.uwfiquypgbonluztkbxo:ApnaPassword@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"

[connections.postgres]
url = "postgresql://postgres.uwfiquypgbonluztkbxo:ApnaPassword@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
